version: '2'

services:
  verdaccio:
    image: pixelcanvas/verdaccio-github-oauth-ui
    container_name: verdaccio-https
    ports:
      - "4873:4873"
    volumes:
        - "./storage:/verdaccio/storage"
        - "./conf:/verdaccio/conf"
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - verdaccio:verdaccio
    environment:
      DOMAINS:
        'npm.threespace.dev -> http://verdaccio:4873'
        # 'temp.threespace.dev -> http://verdaccio:4873'
      CLIENT_MAX_BODY_SIZE: 0
      STAGE: 'production'
      FORCE_RENEW: 'false'
